spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: onList
  servlet:
    multipart:
      enabled: true
      max-file-size: 1GB     # 单个文件大小
      max-request-size: 4GB   # 总文件的上传大小
  redis:
    host: localhost
    database: 0
    port: 6379
    username:
    password:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

mybatis:
  type-aliases-package: com.jeblove.onlyList.entity
  mapper-locations: classpath:/mapper/*.xml

fileLink:
  hashType: MD5
  fileLinkPath: mongodb_onList
  init:
    filename: readme.txt
    fileLinkId: 64687b34528db6326f81d406

jwt:
  secret: onList
  expiration: 5

app:
  security:
    salt: onList
    # 开发测试时false为关闭接口验证
    enabled: true
  share:
    downloadPrefix: download
  backup:
    dir: backups/